### ISSUE TITLE
generatejson.py doesn't have all features

### ISSUE THREAD

**Issue by erikng** [erikng/installapplications#28]
Currently, generatejson.py lacks the following features

scripts
- userscripts
- rootscripts
- donotwait flag
  
stages
 - preflight

**Comment by rickheil** [comment]
Here's a suggested directory structure to make this work with the existing featureset.

```
rootdir/
├── preflight
├── setupassistant
└── userland
    ├── rootscript
    │   ├── donotwait
    │   └── wait
    └── userscript
        ├── donotwait
        └── wait
```

I can also add a switch to make generatejson.py create the directory structure at the passed rootdir since we're introducing more complication for the admin.
Execution order should remain the same since (alphanumeric) - will probably need to sort the python dict to preserve this since a simple listing of files may not capture it between wait/donotwait.

Thoughts?

**Comment by erikng** [comment]
think you are almost there, but missing a few things:

```
rootdir/
├── preflight
├── setupassistant
    ├── pkgs
    │   └── forced
    ├── rootscript
    │   ├── donotwait
    │   └── wait
└── userland
    ├── pkgs
    │   └── forced
    ├── rootscript
    │   ├── donotwait
    │   └── wait
    └── userscript
        ├── donotwait
        └── wait
```

And I like the idea of creating the directory structure with a switch.

**Comment by erikng** [comment]
Addressed with https://github.com/erikng/installapplications/commit/65f1f3873fc7dd98dbf1a5e52d919636df8001ee
